package gt.muni.quejas.model;

/** Catalogo de motivos de rechazo/devolucion de un caso, usable por cualquier rol interno. */
public enum MotivoRechazo {
    CIUDADANO_NO_REGISTRADO,
    IDENTIFICACION_INVALIDA,
    CASO_MALICIOSO,
    CONTENIDO_INAPROPIADO,
    INFORMACION_INCOMPLETA,
    DESCRIPCION_INSUFICIENTE,
    UBICACION_INEXISTENTE,
    EVIDENCIA_NO_VALIDA,
    CATEGORIA_MAL_CLASIFICADA,
    FUERA_DE_COMPETENCIA_MUNICIPAL,
    FUERA_DE_ALCANCE_DEL_SISTEMA,
    DEPARTAMENTO_INCORRECTO,
    NO_CORRESPONDE_AL_DEPARTAMENTO,
    CASO_DUPLICADO,
    CASO_YA_RESUELTO,
    CASO_DESISTIDO,
    ATENCION_NO_RESUELVE_EL_CASO,
    FALTA_EVIDENCIA_DE_RESOLUCION,
    REPORTE_INCONSISTENTE,
    OTRO
}
