-- Esquema principal para login
CREATE TABLE rol (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY primary KEY,
    rol         VARCHAR(50) NOT NULL,
    create_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE departamento (
    id	    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(120) NOT NULL
);

CREATE TABLE estado_usuarios(
    id	    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estado	VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE usuario (
    cui                     VARCHAR(13) PRIMARY KEY,
    nombre                  VARCHAR(150) NOT NULL,
    correo	VARCHAR(100)    NOT NULL UNIQUE,
    password                VARCHAR(150) NOT NULL,
    id_rol                  BIGINT NOT NULL REFERENCES rol(id),
    id_departamento         BIGINT NOT NULL REFERENCES departamento(id),
    id_estado               BIGINT NOT NULL REFERENCES estado_usuarios(id),
    intentos_fallidos       INT NOT NULL DEFAULT 0,
    create_at	            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usuario_creacion	    VARCHAR(50) NOT NULL
);

CREATE TABLE token_recuperacion (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token               VARCHAR(255) NOT NULL UNIQUE,
    cui                 VARCHAR(13) NOT NULL REFERENCES usuario(cui),
    fecha_creacion      TIMESTAMP NOT NULL,
    fecha_expiracion    TIMESTAMP NOT NULL,
    usado              BOOLEAN NOT NULL DEFAULT false
);

-- Datos iniciales
INSERT INTO rol(rol) VALUES
    ('Admin'),
    ('Auxiliar'),
    ('Tecnico'),
    ('Supervisor'),
    ('Jefe');

INSERT INTO departamento (nombre) VALUES
    ('Tecnologia'),
    ('Servicios Publicos'),
    ('Asuntos Municipales'),
    ('Recursos Humanos'),
    ('Tesoreria');

INSERT INTO estado_usuarios(estado) VALUES
    ('Activo'),
    ('Inactivo'),
    ('Bloqueado'),
    ('Ausente');

INSERT INTO usuario (cui, nombre, correo, password, id_rol, id_departamento, id_estado, usuario_creacion) VALUES
    ('1971216190109', 'admin', 'spoconb@miumg.edu.gt', '$2a$10$FfYHZ5Il5pGBn8Hphp5RU.sEAq8dIAHYXH9IiohZZlVwaCsdHaoIm',1, 1, 1, 'system'),
    ('1971216190110', 'nombre_admin2', 'admin2@gmail.com', '$2a$10$FfYHZ5Il5pGBn8Hphp5RU.sEAq8dIAHYXH9IiohZZlVwaCsdHaoIm',1, 1, 2, 'system');